name: noraxlab
description: NORAXLAB - Cyber Elite Content Platform
version: 2.0.4
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.1
  firebase_database: ^10.3.4
  firebase_storage: ^11.3.5
  cloud_firestore: ^4.15.1
  provider: ^6.1.1
  flutter_animate: ^4.1.1+1
  shimmer: ^2.0.0
  cached_network_image: ^3.3.0
  url_launcher: ^6.2.1
  dio: ^5.4.0
  path_provider: ^2.1.1
  permission_handler: ^10.4.4
  rive: ^0.10.1
  liquid_pull_to_refresh: ^3.0.0
  google_fonts: ^4.0.4
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/animations/
    
  fonts:
    - family: Cyber
      fonts:
        - asset: assets/fonts/cyber.ttf
